name: Deploy GH Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Generate config.js (no heredocs)
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${FIREBASE_MEASUREMENT_ID:-}" ]; then
            printf '%s\n' \
              "window.FIREBASE_CONFIG = {" \
              "  apiKey: \"${FIREBASE_API_KEY}\"," \
              "  authDomain: \"${FIREBASE_AUTH_DOMAIN}\"," \
              "  projectId: \"${FIREBASE_PROJECT_ID}\"," \
              "  storageBucket: \"${FIREBASE_STORAGE_BUCKET}\"," \
              "  messagingSenderId: \"${FIREBASE_MESSAGING_SENDER_ID}\"," \
              "  appId: \"${FIREBASE_APP_ID}\"," \
              "  measurementId: \"${FIREBASE_MEASUREMENT_ID}\"" \
              "};" > config.js
          else
            printf '%s\n' \
              "window.FIREBASE_CONFIG = {" \
              "  apiKey: \"${FIREBASE_API_KEY}\"," \
              "  authDomain: \"${FIREBASE_AUTH_DOMAIN}\"," \
              "  projectId: \"${FIREBASE_PROJECT_ID}\"," \
              "  storageBucket: \"${FIREBASE_STORAGE_BUCKET}\"," \
              "  messagingSenderId: \"${FIREBASE_MESSAGING_SENDER_ID}\"," \
              "  appId: \"${FIREBASE_APP_ID}\"" \
              "};" > config.js
          fi
          echo "--- created config.js ---"
          head -n 20 config.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
